sudo: required
services:
  - docker

script:
  - docker run -e CI=true benaroh30/client npm test -- --coverage

after_success:
  #build production dockerfile
  - docker build -t benaroh30/client .
  - echo "$Docker_password" | docker login --username "$Docker_id" --password-stdin
  - docker push benaroh30/client
